Test infra for NAT tests and a simple test
kinvolk/habitat pull request #16
Opened 2018-02-16 18:44 UTC by krnowak

This PR basically adds a concept of zones. Each zone can be in some indirect relationship with other zone - either as a descendant (child) or an ancestor (parent).

Server can be started in a chosen zone and can talk to other servers in the same zone or in parent zones. Servers can't talk to other servers that are in child zones.

Servers in child zones can be exposed in parent zones, so servers in parent zone can have a way to communicate with servers in child zones. Not that it works, because the server itself can't yet handle this case.

The commit message are a bit crappy, but now it's late and it's hard for me to write something decent. Let me know if you want to have something explained.

2018-02-21 14:51 UTC, lilic requested changes

2018-02-21 14:51 UTC, lilic commented on components/butterfly/tests/nat/mod.rs
> +// ZoneInfo stores the relationship information of a zone.
I would rename this to `ZoneRelationInfo`, otherwise it makes me think it's about zone current status. WDYT?

2018-02-21 14:51 UTC, lilic commented on components/butterfly/tests/nat/mod.rs
> +                    format!("no test gossip receiver, should not happen"),
Since it is an error msg, I guess we can assume that this should not happen? I would remove the "should not happen" part.

2018-10-04 09:46 UTC, schu commented
@krnowak I guess this PR can be closed?

2018-10-09 18:47 UTC, krnowak commented
Yes, of course. Closing.

2018-10-09 18:47 UTC, closed without merging