kubernetes, helm: Update to the latest version of the operator
kinvolk/habitat pull request #32
Opened 2018-05-23 14:15 UTC by krnowak

- generate a new version of the manifest (`v1beta2` custom version)
- generate persistent storage fields in the manifest
- generate environment variable fields in the manifest

2018-05-24 11:21 UTC, iaguis requested changes
Some small comments. Otherwise (and taking into account I don't know much rust) looks good. Also, I haven't tested it :)

2018-05-24 11:21 UTC, iaguis commented on components/pkg-export-kubernetes/src/hb.rs
> +            .ok_or_else(|| RenderError::new("Expected the string parameter"))?;
Expected **a** string parameter

2018-05-24 11:21 UTC, iaguis commented on components/pkg-export-kubernetes/src/cli.rs
> +                             <storage class name> is a name of a storage class \
is **the** name of **the** storage class

2018-05-24 11:21 UTC, iaguis commented on components/pkg-export-kubernetes/src/manifest.rs
> +    pub storage: Option<PersistentStorage>,
Also here, should we use `persistent_storage` for consistency?

Along with similar changes in `cli.rs`.

Not a big deal.

2018-05-24 11:21 UTC, iaguis commented on components/pkg-export-kubernetes/src/storage.rs
> +        enum State {
State Machines :heart_eyes:

2018-05-24 11:21 UTC, iaguis commented on components/pkg-export-helm/src/chart.rs
> +                "name": format!("{{{{.Values.{}}}}}", name_var),
braces, braces everywhere. Interesting escaping.

2018-05-24 11:21 UTC, iaguis commented on components/pkg-export-kubernetes/src/error.rs
> +    #[fail(display = "Invalid environment variable \"{}\", must in the form <NAME>=<VALUE>", _0)]
must **be** in the form

2018-05-24 11:21 UTC, iaguis commented on components/pkg-export-kubernetes/src/manifest.rs
> +    pub environment: Vec<EnvVar>,
Since the name in the Habitat type is `env` this should also be `env`. I guess you use `environment` here because of some name clash?

Anyway, not a big deal.

2018-05-24 11:21 UTC, iaguis commented on components/pkg-export-helm/src/chart.rs
> +            "storage": manifest.storage
Same thing about storage and persistent_storage

2018-05-28 13:47 UTC, krnowak commented on components/pkg-export-helm/src/chart.rs
> +                "name": format!("{{{{.Values.{}}}}}", name_var),
Yeah, use double bracket to get a bracket. Tricked me once, when I tried using `\{`.

2018-07-06 15:11 UTC, merged